GET http://localhost:8080/api/users/hello
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJMYXJyeUJpeiIsInN1YiI6ImxhcnJ5IiwiaWF0IjoxNTMyNDk5MTk5LCJleHAiOjE1MzMxMDM5OTksImF1dGhvcml0aWVzIjoiW1JPTEVfQURNSU5dIn0.YT2y_a0pM39Jnuq0C-pcqckY-YEPgmXX2ZCaCXlGHlSXzMMgZrWvmRJRT7YG8j9Fw210uPnE4xvBDtwp-xky-g

###

